apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: add-ons
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/the9thlime/eks-blueprints-addons.git
    targetRevision: HEAD
    path: chart
    helm:
      release: add-ons
      values: |
        grafana:
          enable: true
        kubePrometheusStack:
          enable: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated: {}
